# Generated by Django 4.1.1 on 2022-12-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='TIN_Number',
            field=models.CharField(max_length=25, verbose_name='TIN_Number'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='tire_number',
            field=models.IntegerField(verbose_name='tire_number'),
        ),
    ]
