# Generated by Django 4.1.1 on 2022-12-14 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0002_alter_tire_tin_number_alter_tire_tire_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=25, verbose_name='TIN_Number')),
            ],
        ),
        migrations.AddField(
            model_name='tire',
            name='tire_type',
            field=models.CharField(default='Old', max_length=25, verbose_name='tire_type'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(verbose_name='activity_date')),
                ('tire_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tires.tire')),
            ],
        ),
        migrations.AddField(
            model_name='tire',
            name='activity_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tires.activity'),
        ),
        migrations.AddField(
            model_name='tire',
            name='location_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tires.location'),
        ),
    ]
