# Generated by Django 4.1.1 on 2022-12-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0003_location_tire_tire_type_activity_tire_activity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=25, verbose_name='location'),
        ),
    ]
